export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const STATIONS_SUCCESS = 'STATIONS_SUCCESS';
export const FILTER_STATIONS_SUCCESS = 'FILTER_STATIONS_SUCCESS';
export const REFRESH_STATIONS_SUCCESS = 'REFRESH_STATIONS_SUCCESS';
